export const tourSteps = [
  // ===== DASHBOARD PAGE =====
  {
    id: "dashboard-overview",
    path: "/dashboard",
    target: "#dashboard-header",
    fallbackTarget: '[data-tour="header-banner"]',
    type: "information",
    action: "acknowledge",
    title: "Trang Tiến trình",
    description: "Đây là nơi bạn theo dõi toàn bộ quá trình học tập, quản lý mục tiêu hàng ngày và tích lũy XP.",
  },
  {
    id: "leaderboard",
    path: "/dashboard",
    target: "#leaderboard",
    fallbackTarget: '[data-tour="leaderboard-card"]',
    type: "information",
    action: "acknowledge",
    title: "🏆 Bảng xếp hạng",
    description: "Nơi thi đua học tập cùng các thành viên khác bằng số điểm kinh nghiệm (XP) bạn kiếm được hàng ngày.",
  },
  {
    id: "achievements",
    path: "/dashboard",
    target: "#achievements",
    fallbackTarget: '[data-tour="achievements-card"]',
    type: "information",
    action: "acknowledge",
    title: "🏅 Phòng danh hiệu",
    description: "Phòng danh hiệu ghi nhận những thành tích vinh danh và các cột mốc học tập bạn đã chinh phục.",
  },

  // ===== READER PAGE =====
  {
    id: "upload-document",
    path: "/reader",
    target: "#upload-document",
    fallbackTarget: 'main',
    type: "information",
    action: "acknowledge",
    title: "📄 Tải lên Tài liệu",
    description: "Tải tài liệu của bạn (PDF/TXT/Hình ảnh) hoặc chọn một tài liệu mẫu có sẵn để bắt đầu đọc và học từ.",
  },
  {
    id: "reader-content",
    path: "/reader",
    target: "#reader-content",
    fallbackTarget: 'main',
    type: "information",
    action: "acknowledge",
    title: "📖 Đọc & Tra từ 1-Click",
    description: "Nhấp trực tiếp vào bất kỳ chữ Hán nào trên văn bản để xem nhanh phiên âm Pinyin, nghĩa tiếng Việt và phát âm.",
  },
  {
    id: "save-word",
    path: "/reader",
    target: "#save-word",
    fallbackTarget: 'main',
    type: "information",
    action: "acknowledge",
    title: "⭐ Lưu Từ Vựng",
    description: "Trong popup tra cứu từ mới, nhấn nút 'Lưu từ' để đưa từ vựng đó vào Sổ tay từ vựng cá nhân phục vụ ôn tập.",
  },

  // ===== VOCABULARY PAGE =====
  {
    id: "vocabulary-table",
    path: "/vocabulary",
    target: "#vocabulary-table",
    fallbackTarget: 'main',
    type: "information",
    action: "acknowledge",
    title: "📚 Sổ Tay Từ Vựng",
    description: "Nơi tập hợp toàn bộ từ vựng bạn đã lưu. Bạn có thể nghe phát âm giọng chuẩn, tra Hán Việt, định nghĩa và kiểm tra tiến trình ghi nhớ.",
  },
  {
    id: "vocabulary-actions",
    path: "/vocabulary",
    target: '[data-tour="vocab-actions"]',
    fallbackTarget: '#vocabulary-table',
    type: "information",
    action: "acknowledge",
    title: "⚙️ Các Nút Thao Tác Mới",
    description: "Các nút thao tác mới như Ôn tập ngay, Tạo Flashcard, Xóa giờ đây luôn hiển thị cố định giúp bạn dễ dàng thao tác hàng loạt.",
  },
  {
    id: "vocabulary-select-review",
    path: "/vocabulary",
    target: '[data-tour="vocab-actions"]',
    fallbackTarget: '#vocabulary-table',
    type: "information",
    action: "acknowledge",
    title: "🎯 Tích Chọn & Ôn Tập",
    description: "Khi bạn tích chọn (check) các từ vựng trong danh sách, các nút thao tác này mới sáng lên và cho phép bạn nhấn Ôn tập để đưa các từ đã chọn sang bên Flashcard.",
  },

  // ===== FLASHCARDS PAGE =====
  {
    id: "flashcard-intro",
    path: "/flashcards",
    target: "#select-deck",
    fallbackTarget: 'main',
    type: "information",
    action: "acknowledge",
    title: "🃏 Học qua Flashcards",
    description: "Ôn tập và kiểm tra trí nhớ từ vựng đã lưu bằng hệ thống thẻ Flashcards 3D sinh động.",
  },
  {
    id: "flashcard-flip",
    path: "/flashcards",
    target: "#flashcard",
    fallbackTarget: 'main',
    type: "information",
    action: "acknowledge",
    title: "👆 Lật Thẻ 3D",
    description: "Nhấp vào thẻ Flashcard để lật mặt sau xem Pinyin, Hán Việt và nghĩa tiếng Việt của từ.",
  },
  {
    id: "srs-rating",
    path: "/flashcards",
    target: "#srs-rating",
    fallbackTarget: 'main',
    type: "information",
    action: "acknowledge",
    title: "🧠 Đánh giá ghi nhớ SRS",
    description: "Đánh giá mức độ nhớ từ (Again, Hard, Good, Easy) để thuật toán lặp lại ngắt quãng tự động lên lịch nhắc nhở ôn tập tối ưu cho bạn.",
  }
];

