export const tourSteps = [
  // ===== GIAI ĐOẠN 1: BẢNG ĐIỀU KHIỂN & MỤC TIÊU HỌC TẬP (/dashboard) =====
  {
    id: "step-1",
    page: "/dashboard",
    target: '[data-tour="header-banner"] button',
    fallbackTarget: '[data-tour="header-banner"]',
    title: "1. Đổi Mục Tiêu Phút Học",
    description: "Nhấp vào nút 'Sửa mục tiêu' để chọn thời gian học tập bạn muốn đạt được mỗi ngày.",
    action: "click",
    actionHint: "👉 Nhấp vào nút 'Sửa mục tiêu' trên thẻ Bảng điều khiển",
  },
  {
    id: "step-2",
    page: "/dashboard",
    target: '[data-tour="goal-presets"] button',
    fallbackTarget: '[data-tour="header-banner"]',
    title: "2. Thiết Lập Mức Thời Gian Học",
    description: "Nhấp chọn một mức thời gian (30P, 60P, 90P) để lưu mục tiêu mới.",
    action: "click",
    actionHint: "👉 Nhấp chọn số phút học (30P / 60P)",
  },
  {
    id: "step-3",
    page: "/dashboard",
    target: '[data-tour="stat-cards"] > div:nth-child(3)',
    fallbackTarget: '[data-tour="stat-cards"]',
    title: "3. Theo Dõi Chuỗi Streak & SRS",
    description: "Đây là 4 Thẻ thống kê nhanh giúp bạn theo dõi Chuỗi lửa Streak 🔥 và số từ vựng đến hạn ôn tập.",
    action: "click",
    actionHint: "👉 Nhấp vào thẻ 'Sổ tay từ vựng' hoặc vùng thống kê",
  },
  {
    id: "step-4",
    page: "/dashboard",
    target: '[data-tour="timer-button"]',
    fallbackTarget: '.hanora-site-header',
    title: "4. Đồng Hồ Pomodoro Học Tập",
    description: "Bấm nút 'Đồng hồ' trên Menu Header để bật/ẩn widget đếm ngược thời gian nổi.",
    action: "click",
    actionHint: "👉 Nhấp vào nút 'Đồng hồ' trên thanh Header",
  },
  {
    id: "step-5",
    page: "/dashboard",
    target: '[data-tour-nav="/reader"]',
    fallbackTarget: '.hanora-site-header',
    title: "5. Mở Trang Dịch Thuật",
    description: "Nhấp vào mục 'Dịch thuật' trên thanh Menu Header để sang trang Đọc tài liệu Tiếng Trung.",
    action: "navigation",
    targetRoute: "/reader",
    actionHint: "👉 Nhấp vào mục 'Dịch thuật' trên thanh Menu Header",
  },

  // ===== GIAI ĐOẠN 2: DỊCH THUẬT & ĐỌC TÀI LIỆU PDF (/reader) =====
  {
    id: "step-6",
    page: "/reader",
    target: 'main',
    fallbackTarget: '.hanora-site-header',
    title: "6. Đọc Tài Liệu & 1-Click Tra Từ",
    description: "Trang Dịch Thuật hỗ trợ đọc tài liệu PDF/văn bản Tiếng Trung & nhấp 1-click xem Pinyin, Hán Việt và lưu từ.",
    action: "click",
    actionHint: "👉 Nhấp vào khu vực Đọc tài liệu để tiếp tục",
  },
  {
    id: "step-7",
    page: "/reader",
    target: '[data-tour-nav="/vocabulary"]',
    fallbackTarget: '.hanora-site-header',
    title: "7. Mở Sổ Tay Từ Vựng",
    description: "Bây giờ hãy nhấp vào mục 'Từ vựng' trên Menu Header để xem Sổ tay chứa tất cả các từ đã lưu.",
    action: "navigation",
    targetRoute: "/vocabulary",
    actionHint: "👉 Nhấp vào mục 'Từ vựng' trên thanh Menu Header",
  },

  // ===== GIAI ĐOẠN 3: SỔ TAY TỪ VỰNG CÁ NHÂN (/vocabulary) =====
  {
    id: "step-8",
    page: "/vocabulary",
    target: 'main',
    fallbackTarget: '.hanora-site-header',
    title: "8. Sổ Tay Từ Vựng Cá Nhân",
    description: "Quản lý danh sách từ vựng cá nhân, nghe phát âm audio, xem câu ví dụ và chuẩn bị cho bài ôn tập.",
    action: "click",
    actionHint: "👉 Nhấp vào bảng từ vựng để tiếp tục sang trang Flashcards",
  },
  {
    id: "step-9",
    page: "/vocabulary",
    target: '[data-tour-nav="/flashcards"]',
    fallbackTarget: '.hanora-site-header',
    title: "9. Mở Trang Flashcard",
    description: "Nhấp vào mục 'Flashcard' trên Menu Header để luyện tập lật thẻ 3D và ghi nhớ từ vựng lâu dài.",
    action: "navigation",
    targetRoute: "/flashcards",
    actionHint: "👉 Nhấp vào mục 'Flashcard' trên thanh Menu Header",
  },

  // ===== GIAI ĐOẠN 4: FLASHCARDS 3D & THUẬT TOÁN SRS (/flashcards) =====
  {
    id: "step-10",
    page: "/flashcards",
    target: 'main',
    fallbackTarget: '.hanora-site-header',
    title: "10. Hoàn Thành Chuyến Khám Phá 🎉",
    description: "Bạn đã hoàn thành việc khám phá toàn bộ 4 phân hệ chính của website Hanora!",
    action: "click",
    actionHint: "👉 Nhấp hoàn thành tour và nhận thưởng +50 XP",
  }
];
